### ISSUE TITLE
Should fetch call revert?

### ISSUE THREAD

**Issue by philipp2310** [project-alice-assistant/AliceGit#1]
Git.py line 191 method fetch calls self.revert()
![image](https://user-images.githubusercontent.com/41761223/147953515-958a95c0-f10b-4166-98ca-ff2eda6db260.png)

fetch should only get the remote changes, not modify anything local?

(I'll edit it - just want to make sure my idea is correct ;))

**Comment by Psychokiller1888** [comment]
Hmmm, correct :) Pull should revert if forced, not fetch

**Comment by philipp2310** [comment]
👍
![image](https://user-images.githubusercontent.com/41761223/147954374-4faa8042-b9f5-48b0-88dc-a6a19d244837.png)
pull already has the revert logic.
